# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import nokia_rib_api_pb2 as nokia__rib__api__pb2


class RibApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Modify = channel.stream_stream(
        '/Nokia.SROS.RibApi/Modify',
        request_serializer=nokia__rib__api__pb2.ModifyRequest.SerializeToString,
        response_deserializer=nokia__rib__api__pb2.ModifyResponse.FromString,
        )
    self.GetVersion = channel.unary_unary(
        '/Nokia.SROS.RibApi/GetVersion',
        request_serializer=nokia__rib__api__pb2.VersionRequest.SerializeToString,
        response_deserializer=nokia__rib__api__pb2.VersionResponse.FromString,
        )


class RibApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Modify(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RibApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Modify': grpc.stream_stream_rpc_method_handler(
          servicer.Modify,
          request_deserializer=nokia__rib__api__pb2.ModifyRequest.FromString,
          response_serializer=nokia__rib__api__pb2.ModifyResponse.SerializeToString,
      ),
      'GetVersion': grpc.unary_unary_rpc_method_handler(
          servicer.GetVersion,
          request_deserializer=nokia__rib__api__pb2.VersionRequest.FromString,
          response_serializer=nokia__rib__api__pb2.VersionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Nokia.SROS.RibApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
